### ISSUE TITLE
example returning error 

### ISSUE THREAD

**Issue by DoaneAS** [broadinstitute/SignatureAnalyzer-GPU#10] opened 2019-08-15 19:48 UTC
Hi, 

I followed the instructions for installing, and running the example returns an error.

Command from example:
```
python SignatureAnalyzer-GPU.py --data example_data/POLEMSI_counts_matrix.txt \
    --max_iter=100000 --output_dir POLEMSI_EXAMPLE \
    --prior_on_W L1 --prior_on_H L2 --labeled
```

The process appears to run, but fails before completing.
The end of the output is:

```
nit=6550	objective=-48458610.0	beta_div=178055.72	lambda=4.4322047	del=1.1551455e-06	K=10	sumW=5379.1426	sumH=1297.3717
nit=6560	objective=-48458610.0	beta_div=178055.69	lambda=4.4322104	del=1.0829373e-06	K=10	sumW=5379.151	sumH=1297.3701
Traceback (most recent call last):
  File "SignatureAnalyzer-GPU.py", line 176, in <module>
    main()
  File "SignatureAnalyzer-GPU.py", line 171, in main
    args.prior_on_W, args.prior_on_H, args.K0, args.tolerance,args.max_iter)
ValueError: too many values to unpack (expected 3)
```

Python environment is:
```
# packages in environment at /gpfs/commons/home/adoane/anaconda3/envs/sig:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
arrow-cpp                 0.11.1          py36h0e61e49_1004    conda-forge
blas                      1.1                    openblas    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py36_1    conda-forge
cffi                      1.12.3           py36h8022711_0    conda-forge
cudatoolkit               9.0                  h13b8566_0
cycler                    0.10.0                     py_1    conda-forge
dask-core                 2.2.0                      py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
feather-format            0.4.0                   py_1003    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
imageio                   2.5.0                    py36_0    conda-forge
intel-openmp              2019.4                      243
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.0.10            h57b8799_1003    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
matplotlib                3.1.0                    py36_0    conda-forge
matplotlib-base           3.1.0            py36h5f35d83_0    conda-forge
mkl                       2019.4                      243
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
ninja                     1.9.0                h6bb024c_0    conda-forge
numpy                     1.14.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pandas                    0.23.0                   py36_1    conda-forge
parquet-cpp               1.5.1                         3    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pillow                    6.1.0            py36h6b7be26_1    conda-forge
pip                       19.2.2                   py36_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyarrow                   0.11.1          py36hbbcf98d_1002    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py36hcca6a23_2    conda-forge
python                    3.6.7             h357f687_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytorch                   1.1.0           py3.6_cuda9.0.176_cudnn7.5.1_0    pytorch
pytz                      2019.2                     py_0    conda-forge
pywavelets                1.0.3            py36hd352d35_1    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scikit-image              0.13.1                   py36_0    conda-forge
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.1.0           py36_blas_openblash7943236_201  [blas_openblas]  conda-forge
setuptools                41.0.1                   py36_0    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
thrift-cpp                0.12.0            h0a07b25_1002    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
toolz                     0.10.0                     py_0    conda-forge
torchvision               0.3.0           py36_cu9.0.176_1    pytorch
tornado                   6.0.3            py36h516909a_0    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```

Thanks,
Ashley

**Comment by amarotaylor** [comment] 2019-08-15 23:39
Hey Ashley,

Thanks for pointing this out to me. I accidentally introduced a bug performing an experiment for reviewers :). Fixed now. Should be good to go. 

Thanks,
Amaro

**Closed by amarotaylor** 2019-08-15 23:39 UTC

**Comment by DoaneAS** [comment] 2019-08-16 17:21
Amaro,
Excellent, thank you!

**Comment by DoaneAS** [comment] 2019-08-16 17:41
Hi Amaro,

I actually get a similar error now when running the example with `--parameters file`, see below. Hopefully another easy fix.  Much appreciated.

```
nit=11710	objective=-2071395.0	beta_div=170504.86	lambda=4.7764454	del=2.594519e-07	K=12	sumW=5796.9927	sumH=1453.0645
Traceback (most recent call last):
  File "SignatureAnalyzer-GPU.py", line 176, in <module>
    main()
  File "SignatureAnalyzer-GPU.py", line 168, in main
    run_parameter_sweep(parameters,data,args,Beta)
  File "SignatureAnalyzer-GPU.py", line 60, in run_parameter_sweep
    args.prior_on_W, args.prior_on_H, parameters.iloc[idx]['K0'], args.tolerance,args.max_iter)
  File "/gpfs/commons/home/adoane/tools/SignatureAnalyzer-GPU/ARD_NMF.py", line 122, in run_method_engine
    results.initalize_data(a,phi,b,W_prior,H_prior,Beta,K0)
  File "/gpfs/commons/home/adoane/tools/SignatureAnalyzer-GPU/ARD_NMF.py", line 94, in initalize_data
    self.bcpu = np.true_divide(np.mean(self.V)*np.sqrt(2)*gamma(self.a-3/2),self.K0*np.sqrt(np.pi)*gamma(self.a))
  File "/gpfs/commons/home/adoane/anaconda3/envs/sig/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2954, in mean
    return mean(axis=axis, dtype=dtype, out=out, **kwargs)
TypeError: mean() missing 3 required positional argument: "dim", "keepdim", "dtype"
```
    
many thanks,
Ashley

**Comment by amarotaylor** [comment] 2019-08-16 20:34
Hey Ashley,

Im unable to reproduce this bug. It seems like your version of numpy.mean() **requires** 3 arguments? Not sure if the openblas version is the issue. 
>  numpy                     1.14.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
